pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f app/pom.xml clean package'
            }
            post {
                success {
                    echo "Now archiving the artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in staging environment') {
            steps {
                build job: 'DeployApplication'
            }
        }
        stage('Deploy to production') {
            steps {
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'DeployApplicationToProductionEnv'
            }
        }
    }
}