pipeline {
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f app/pom.xml clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}